server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/company_managementt
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: royalhsyn
    password: Qara1607@
  jpa:
    show-sql: true

